const INITIAL_DATA = 'ASSIGN_DATA';
const UPDATE_NICKNAME = 'UPDATE_NICKNAME';
const UPDATE_FIRSTNAME = 'UPDATE_FIRSTNAME';
const UPDATE_LASTNAME = 'UPDATE_LASTNAME';
const UPDATE_EMAIL = 'UPDATE_EMAIL';
const UPDATE_PHONE = 'UPDATE_PHONE';
const UPDATE_SELECTEDSTORE = 'UPDATE_SELECTEDSTORE';
const DELETE_DATA = 'DELETE_DATA';
export {INITIAL_DATA, UPDATE_NICKNAME, UPDATE_FIRSTNAME, UPDATE_LASTNAME, UPDATE_EMAIL, UPDATE_PHONE, UPDATE_SELECTEDSTORE, DELETE_DATA}
