const INITIAL_DATA = 'ASSIGN_DATA';
const UPDATE_EMPID = 'UPDATE_EMPID';
const UPDATE_ROLE = 'UPDATE_ROLE';
const UPDATE_TOKEN = 'UPDATE_TOKEN';
const UPDATE_DATA = 'UPDATE_DATA';
const UPDATE_SELECTEDSTORE = 'UPDATE_SELECTEDSTORE';
const UPDATE_STORE = 'UPDATE_STORE';
const UPDATE_IMGPROFILE = 'UPDATE_IMGPROFILE';
const INACTIVE_TIME = 'INACTIVE_TIME';
const UPDATE_LOGIN ='UPDATE_LOGIN';
const DELETE_DATA = 'DELETE_DATA';
export {INITIAL_DATA, UPDATE_EMPID, INACTIVE_TIME, UPDATE_ROLE, UPDATE_DATA, UPDATE_TOKEN, UPDATE_STORE, UPDATE_IMGPROFILE, UPDATE_LOGIN, UPDATE_SELECTEDSTORE, DELETE_DATA}
